In [ ]:
import pandas as pd
df = pd.read_csv('candy_crush_preprocessed (2).csv')
df = df.dropna().reset_index().drop(columns=['index'])
df_pre = df['stem']
df_pre.info()

<class 'pandas.core.series.Series'>
RangeIndex: 500 entries, 0 to 499
Series name: stem
Non-Null Count  Dtype
--------------  -----
500 non-null    object
dtypes: object(1)
memory usage: 4.0+ KB

In [ ]:
import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Mengubah teks menjadi matriks TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df_pre)
df_FE = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df_FE

,000,003,010,10,10000,102,10308,12,12404,129,...,मस,हब,এই,একট,জন,মজ,যখন,রক,ꙇїҝє,ꚍө
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Tokenize Sentence

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
from nltk import word_tokenize
from tqdm import tqdm

sentences = [word_tokenize(tweet.lower()) for tweet in tqdm(df_pre)]
sentences

100%|██████████| 500/500 [00:00<00:00, 7288.03it/s]

[['experi', 'good', 'would', 'better', 'offlin', 'onlin'],
 ['best',
  'game',
  'play',
  'alot',
  'challeng',
  'win',
  'mani',
  'good',
  'gift',
  'suggest',
  'app',
  'nice',
  'play'],
 ['ad', 'keep', 'take', 'app', 'lose', 'progress'],
 ['recent', 'updat', 'life', 'save', 'ad', 'game'],
 ['brilliant', 'game', 'love', 'addict', 'ever', 'stop', 'play'],
 ['love', 'game', 'fun', 'relax', 'n'],
 ['candi',
  'crush',
  'alway',
  'game',
  'famili',
  'like',
  'pass',
  'gener',
  'gener',
  'turn',
  'play',
  'love',
  'game',
  'also',
  'enjoy',
  'play',
  'mother',
  'realli',
  'hope',
  'child',
  'abl',
  'also',
  'enjoy',
  'way',
  'give',
  '5',
  'star'],
 ['game', 'fairli', 'fantast'],
 ['best',
  'game',
  'peopl',
  'much',
  'free',
  'time',
  'calm',
  'game',
  'game',
  'run',
  'everi',
  'devic',
  'smooth'],
 ['love', 'game'],
 ['need',
  'email',
  'acc',
  'child',
  'game',
  'moron',
  'thiev',
  'money',
  'children'],
 ['super', 'fun', 'relax', 'play', 'come', 'join', 'fun'],
 ['game',
  'huge',
  'scam',
  'get',
  'money',
  'legendari',
  'level',
  'complet',
  'unbeat',
  'wors',
  'pin',
  'perman',
  'save',
  'delet',
  'complet',
  'collect',
  'hard',
  'time',
  'tri',
  'email',
  'game',
  'maker',
  'advic',
  'onedr',
  'immedi',
  'share',
  'pin',
  'get',
  'game',
  'exercis',
  'futil'],
 ['someon', 'level', 'illeg', 'bad'],
 ['enjoy', 'lazi', 'time'],
 ['good', 'like', 'game', 'interest', 'good', 'timw', 'pass'],
 ['nice', 'entertain'],
 ['love', 'great', 'way', 'calm', 'mind'],
 ['game',
  'stuck',
  'level',
  '680',
  'give',
  'choic',
  'extra',
  'move',
  'nit',
  'work'],
 ['awesom',
  'play',
  'candi',
  'crush',
  'last',
  'eleven',
  'year',
  'never',
  'get',
  'bore',
  'game',
  'close',
  'heart'],
 ['happen',
  'reward',
  'ad',
  'watch',
  'ad',
  'normal',
  'get',
  'reward',
  'end',
  'ad',
  'goe',
  'back',
  'reward',
  'happen',
  'pre',
  'level',
  'get',
  'extra',
  'move',
  'end',
  'level',
  'sweet',
  'cinema',
  'sort',
  'pleas'],
 ['bast', 'game', 'time'],
 ['game', 'fun', 'play', 'also', 'offlin', 'game', 'think'],
 ['addict', 'game', 'play', 'get', 'free', 'time'],
 ['tire', 'ur', 'ad', 'go', 'away'],
 ['alway', 'fun', 'play', 'candi', 'crush', 'saga'],
 ['strateg', 'fun', 'worth', 'play', 'dismal', 'mobil', 'space'],
 ['stop', 'frozen', 'ad', 'play', 'keep', 'restart', 'game'],
 ['love',
  'game',
  'play',
  'year',
  'relax',
  'wish',
  'could',
  'post',
  'process',
  'facebook'],
 ['user',
  'download',
  'game',
  'mean',
  'play',
  'user',
  'keep',
  'show',
  'distract',
  'unusu',
  'move',
  'user',
  'play',
  'fix',
  'send',
  'mail',
  'download',
  'uninstal'],
 ['give',
  'us',
  'move',
  'play',
  'harder',
  'level',
  'like',
  '36',
  'move',
  'pleas'],
 ['good', 'player', 'pay', 'money'],
 ['useless',
  'game',
  'like',
  'win',
  'gold',
  'bar',
  'episod',
  'race',
  'hurt',
  'tri',
  'mean',
  'lose',
  'gold',
  'bar',
  'make',
  'game',
  'tough',
  '10',
  'gold',
  'bar',
  'get',
  '5',
  'move',
  'yet',
  'know',
  'hard',
  '10',
  'gold',
  'bar'],
 ['bad', 'game', 'quit', 'addict'],
 ['good', 'relax', 'space'],
 ['sere',
  'beli',
  'gold',
  'bar',
  'tp',
  'pa',
  'purchas',
  'tiba2',
  'connect',
  'lost',
  'padah',
  'udah',
  'terbayar',
  'tp',
  'gold',
  'bar',
  'tidak',
  'ada'],
 ['game', 'enjoy'],
 ['help', 'alot', 'calm', 'thought'],
 ['worst', 'game', 'ever', 'bore'],
 ['like',
  'game',
  'ad',
  'start',
  'easi',
  'play',
  'go',
  'hard',
  'one',
  'favourit',
  'game',
  'candi',
  'crush',
  'saga'],
 ['perpetu', 'awesom', 'experi', 'stop', 'play'],
 ['enjoy', 'challeng'],
 ['get', 'enough', 'game'],
 ['releas', 'mention', 'alway', 'want', 'play'],
 ['game', 'harder', 'know', 'game', 'fun', 'crazi', 'tri', 'love'],
 ['lot', 'fun'],
 ['love',
  'becom',
  'harder',
  'hard',
  'level',
  'anoth',
  'make',
  'longer',
  'enjoy',
  'game'],
 ['play', 'almost', 'decad', 'still', 'fun', 'use'],
 ['bohat', 'e', 'achi', 'game', 'hai', 'instal', 'fun'],
 ['use',
  'love',
  'play',
  'wake',
  'break',
  'work',
  'sometim',
  'last',
  'patch',
  'money',
  'grab',
  'full',
  'booster',
  '20',
  'min',
  'parti',
  'popper',
  'still',
  'lose',
  'level',
  'got',
  'last',
  '8',
  'dollar',
  'greedi',
  'dev',
  'uninstal',
  'like',
  '10',
  'year',
  'play',
  'eat',
  'satchel',
  'richard'],
 ['best', 'game', 'tbh'],
 ['level',
  'sure',
  'bias',
  'player',
  'lose',
  'streak',
  'spend',
  'money',
  'extra',
  'move'],
 ['much', 'fun', 'love'],
 ['enjoy', 'play', 'game', 'relax', 'possibl', 'get', 'old', 'game', 'back'],
 ['best', 'game', 'world'],
 ['khali',
  'samay',
  'mai',
  'ye',
  'candi',
  'cara',
  'game',
  'bahut',
  'achchha',
  'hai',
  'aur',
  'man',
  'bhi',
  'lagta',
  'hai'],
 ['like',
  'other',
  'said',
  'game',
  'use',
  'fun',
  'level',
  'went',
  'challeng',
  'ridicul',
  'final',
  'straw',
  'came',
  'play',
  'level',
  '8363',
  'fail',
  'quit',
  'time',
  'game',
  'prompt',
  'purchas',
  'move',
  'enough',
  'gold',
  'bar',
  'sinc',
  'final',
  'gotten',
  'game',
  'almost',
  'offer',
  '83',
  'move',
  'went',
  'turn',
  'game',
  'gener',
  'creat',
  'thing',
  'need',
  'complet',
  'game',
  'gone'],
 ['good', 'game', 'make', 'feel', 'fun'],
 ['love', 'game', '4', 'devic'],
 ['excel',
  'game',
  'new',
  'addit',
  'card',
  'game',
  'callect',
  'spoon',
  'puzzl',
  'think',
  'best',
  'game',
  'everyon'],
 ['go',
  'give',
  '3',
  'star',
  'coupon',
  'anymor',
  'think',
  'bull',
  'cape',
  'start',
  'play',
  'game',
  'long',
  'time',
  'ago',
  'like',
  'like',
  'game',
  'wish',
  'would',
  'put',
  'coupon',
  'back',
  'would',
  'lot',
  'better',
  'could',
  'get',
  'stuff'],
 ['great', 'love', 'much'],
 ['great',
  'fun',
  'addict',
  'angri',
  'problem',
  'latest',
  'updat',
  'keep',
  'say',
  'need',
  'internet',
  'connect',
  'internet',
  'connect',
  'fun',
  'without',
  'internet',
  'connect',
  'pleas',
  'fix'],
 ['interest', 'keep', 'busi'],
 ['like', 'satisfi', 'crush', 'candi'],
 ['best', 'game'],
 ['great', 'game', 'wait', 'someth'],
 ['game',
  'good',
  'free',
  'harder',
  'level',
  'seem',
  'design',
  'mainli',
  'make',
  'player',
  'spend',
  'money',
  '“',
  'race',
  '”',
  'featur',
  'push',
  'us',
  'win',
  'quickli',
  'first',
  'game',
  'give',
  'easi',
  'win',
  'coin',
  'later',
  'level',
  'becom',
  'harder',
  'win',
  'race',
  'use',
  'coin',
  'next',
  'race',
  'coin',
  'gone',
  'end',
  'buy',
  'slowli',
  'becom',
  'habit',
  'also',
  'understand',
  'work'],
 ['give', '10', '5'],
 ['lot', 'fun'],
 ['love',
  'play',
  'candi',
  'crush',
  'love',
  'live',
  'event',
  'even',
  'chanc',
  'go',
  'live',
  'wish',
  'game',
  'thing'],
 ['msg', 'box', 'wont', 'open'],
 ['super', 'game', 'like', 'like', 'free', 'fire'],
 ['hung', '129', 'can', 'not', 'figur', 'play'],
 ['best',
  'candi',
  'crush',
  'day',
  'ever',
  'open',
  'play',
  'almost',
  'everi',
  'day'],
 ['booster',
  'issu',
  'load',
  'commerci',
  'black',
  'screen',
  'even',
  'tri',
  'give',
  'enough',
  'time',
  'crash',
  'lose',
  'everyth',
  'get',
  'annoy',
  'point',
  'uninstal',
  'app'],
 ['love', 'play', 'pass', 'time'],
 ['like', 'game'],
 ['advertis',
  'reward',
  'system',
  'work',
  'hard',
  'play',
  'help',
  'custom',
  'servic',
  'bad',
  'fix',
  'write',
  'mail'],
 ['nice', 'play'],
 ['tri',
  'play',
  'today',
  'take',
  'break',
  'year',
  'gameplay',
  'pretti',
  'much',
  'rememb',
  'geez',
  'mani',
  'pop',
  'up',
  'want',
  'swear',
  'almost',
  '10',
  'thing',
  'pop',
  'row',
  'want',
  'play',
  'coupl',
  'level',
  'sheesh'],
 ['mean', 'higher', 'goe', 'easier', 'soooooo', 'funn'],
 ['game',
  'least',
  '6',
  'month',
  'longer',
  'play',
  'long',
  'time',
  'open',
  'app',
  'play',
  'today',
  'tell',
  'can',
  'not',
  'play',
  'unless',
  'accept',
  'term',
  'polici',
  'accept',
  'term',
  'polici',
  'first',
  'download',
  'app',
  'get',
  'told',
  'can',
  'not',
  'play',
  'right',
  'candi',
  'crush',
  'guess',
  'play',
  'game',
  'chang',
  'anyway',
  'hardli',
  'play',
  'first',
  '10',
  'minut',
  'popup'],
 ['like',
  'type',
  'game',
  'feel',
  'vital',
  'everyon',
  'life',
  'could',
  'gotten',
  'five',
  'first',
  'soundtrack',
  'like',
  'whistl',
  'nice',
  'dont',
  'like',
  'current',
  'one',
  'realli',
  'hit',
  'spot',
  'make',
  'feel',
  'relax',
  'think'],
 ['love', 'candi', 'crush', 'still', 'like', 'candi', 'crush'],
 ['amaz', 'play'],
 ['need', 'spend', 'money', 'progress', 'stupid'],
 ['fun',
  'day',
  'quickli',
  'get',
  'complic',
  'pass',
  'board',
  'without',
  'spend',
  'money',
  'liter',
  'mathemat',
  'enough',
  'turn',
  'spend',
  'cash'],
 ['play',
  'app',
  'sinc',
  '2016',
  'amaz',
  'game',
  'user',
  'friendli',
  'hard',
  'human',
  'imposs'],
 ['game', 'fevarit', 'game'],
 ['love', 'see', 'boo', 'ster'],
 ['good', 'nice', 'game', 'play'],
 ['fantast',
  'awesom',
  'realli',
  'enjoy',
  'game',
  'game',
  'fun',
  'love',
  'use',
  'colorbomb',
  'hard'],
 ['well', 'nice', 'play'],
 ['love', 'game', 'wish', 'earn', 'play'],
 ['good', 'game', 'full', 'time', 'pass'],
 ['nice', 'game', 'love'],
 ['suggest',
  'make',
  'long',
  'ad',
  'time',
  'get',
  'reward',
  'time',
  'watch',
  'ad',
  'need',
  'award'],
 ['enjoy', 'game', 'start', 'crash', 'close', 'time', 'hope', 'fix', 'issu'],
 ['download',
  'game',
  'look',
  'stupid',
  'paid',
  'actor',
  'confirm',
  'game',
  'stupid',
  'peopl',
  'especi',
  'coupl',
  'man',
  'behav',
  'like',
  'wimp',
  'ladi',
  'like',
  'witch',
  'one',
  'bun',
  'eye',
  'big',
  'look',
  'like',
  'marbl',
  'stupid',
  'bimbo',
  'make',
  'claim',
  'play',
  'everyday',
  'smart',
  'stop',
  'push',
  'ad',
  'peopl',
  'wast',
  'time'],
 ['candi', 'crush', 'crush', '8171'],
 ['play',
  'game',
  'alway',
  'long',
  'road',
  'trip',
  'recommend',
  'stress',
  'reliev',
  'satisfi',
  'swipe',
  'play'],
 ['app', 'crash', '3', 'time', '30', 'minut', 'unstabl', 'app'],
 ['save',
  'money',
  'game',
  'still',
  'fun',
  'find',
  'crash',
  'win',
  'gold',
  'finish',
  'level',
  'avoid',
  'app',
  'purchas',
  'much',
  'possibl',
  'also',
  'purchas',
  'cost',
  'get',
  'less'],
 ['love', 'time'],
 ['absolut', 'love', 'game', 'best', 'ever'],
 ['iov', 'play', 'game', 'distract', 'lot', 'help', 'get', 'stress'],
 ['ad', 'appear', 'get', 'chanc', 'game'],
 ['love', 'far', 'candi', 'crush', 'favorit', 'game'],
 ['edit',
  'start',
  'im',
  'gut',
  'brilliant',
  'game',
  'distract',
  'day',
  'stress',
  'argh',
  'updat',
  'play'],
 ['time', 'bahot', 'khrab', 'hota', 'hai'],
 ['like',
  'puzzl',
  'game',
  'game',
  'realli',
  'good',
  'color',
  'fantast',
  'buy',
  'time'],
 ['great', 'game', 'pass', 'time', 'love', 'pass', 'level'],
 ['sinc',
  'yesterday',
  'booster',
  'wheel',
  'count',
  'time',
  'till',
  'next',
  'one',
  'ad',
  'hour',
  'decreas',
  'next',
  'booster',
  '5',
  'hour',
  'midnight',
  'show',
  '17h15',
  'time',
  '17h15',
  'hope',
  'fix',
  'booster',
  'wheel',
  'need',
  'also',
  'made',
  'room',
  'imposs',
  'pass',
  'without',
  'pay',
  'gold',
  'extra',
  'move',
  'discourag',
  'continu',
  'play'],
 ['realli', 'love', 'game', 'take', 'stress', 'away', 'play', 'game'],
 ['fun', 'especi', 'special', 'competit'],
 ['play',
  'everi',
  'day',
  'work',
  'home',
  'fun',
  'game',
  'play',
  'ppl',
  'work',
  'play',
  'play',
  'day',
  'laptop'],
 ['bore', 'bad', 'download'],
 ['game', 'good', 'put', 'ad', 'come', 'want', 'ad', 'loss', 'tha', 'game'],
 ['love', 'play', 'snowi', 'day', 'love', 'love'],
 ['start',
  'today',
  'toni',
  'gibb',
  'realli',
  'love',
  'enjoy',
  'play',
  'candi',
  'crush',
  'saga',
  'star',
  'game',
  'start'],
 ['play',
  'game',
  'year',
  'felt',
  'bad',
  'forget',
  'login',
  'detail',
  'back',
  'nevertheless',
  'grate',
  'back',
  'track',
  'level',
  '6000',
  'thank',
  'candi',
  'crush',
  'love',
  'game'],
 ['good', 'game', 'love', 'game'],
 ['level', '12404', 'need', 'attent', 'asap', 'move', 'pleas', 'check'],
 ['far', 'glitch', 'great', 'game'],
 ['hi',
  'first',
  'time',
  'play',
  'candi',
  'crush',
  'level',
  '4o',
  'almost',
  'without',
  'loos',
  'heart',
  'fun',
  'far',
  'hope',
  'next',
  'level',
  'pretti',
  'challeng',
  'thank'],
 ['time',
  'par',
  'kaam',
  'nhi',
  'karta',
  'inka',
  'sarvesh',
  'video',
  'upload',
  'kar',
  'skta',
  'hu'],
 ['good', 'game', 'world', 'amaz'],
 ['love', 'candi', 'crush'],
 ['good', 'game', 'love', 'fev', 'love', 'play', 'game'],
 ['relax', 'game', 'ever', 'love'],
 ['fun', 'app', 'purchas', 'ad', 'keep', 'pop'],
 ['earlier',
  'game',
  'good',
  'level',
  'easi',
  'tough',
  'look',
  'like',
  'way',
  'move',
  'ahead',
  'apart',
  'buy',
  'booster',
  'without',
  'booster',
  'extra',
  'move',
  'end',
  'can',
  'not',
  'win',
  'game',
  'feel',
  'like',
  'busi',
  'less',
  'like',
  'game',
  'instal',
  'app',
  'alway',
  'end',
  'uninstal',
  '2',
  'day',
  'due',
  'problem',
  'similar',
  'game',
  'feel',
  'good',
  'play',
  'candi',
  'crush',
  'lost',
  'charm'],
 ['best', 'game', 'saga', 'candi', 'crush', 'saga'],
 ['candi', 'crush', 'saga', 'good', 'game'],
 ['great', 'game', 'lot', 'fun'],
 ['good',
  'time',
  'pass',
  'noth',
  'give',
  'cash',
  'reward',
  'buy',
  'booster',
  'gold',
  'bar',
  'life',
  'game',
  'spend',
  'money',
  'game',
  'would',
  'rather',
  'like',
  'uninstal',
  'instead',
  'buy',
  'thing',
  'game',
  'can',
  'not',
  'shed',
  'cash',
  'reward',
  'spend',
  'singl',
  'penny¿',
  '¿',
  'addict',
  'mad',
  'game',
  'never'],
 ['love', 'game', 'iam', 'free', 'time'],
 ['excel', 'game', 'excit', 'way', 'pay', 'time'],
 ['pretti', 'fun', 'also', 'time', 'consum'],
 ['top',
  'game',
  'well',
  'entertain',
  'keep',
  'good',
  'work',
  'creator',
  'still',
  'play',
  '5yr'],
 ['enjoy', 'everi', 'minut', 'game', 'play', 'super', 'cool'],
 ['iam', 'get', 'ad', 'reward'],
 ['like',
  'level',
  '300',
  'butterfli',
  'collect',
  'side',
  'play',
  'froze',
  'lost',
  'progress',
  'longer',
  'play',
  'ye',
  'realli',
  'enjoy',
  'game',
  'til',
  'happen',
  'also',
  'ive',
  'download',
  '2',
  'time',
  'froze',
  'time',
  'like',
  'game',
  'cant',
  'play',
  'freez',
  'sorri'],
 ['consist',
  'reward',
  'sometim',
  'chang',
  'candi',
  'color',
  'move',
  'stripe',
  'candi',
  'get',
  'chocol',
  'ball',
  'next',
  'add',
  'shade',
  'area',
  'remov'],
 ['fun',
  'get',
  'mani',
  'ad',
  'sooooo',
  'annoy',
  'happen',
  'oh',
  'that',
  'yayyyyyi'],
 ['candi', 'crush', 'fun', 'way', 'take', 'mind', 'stress', 'news'],
 ['latest', 'updat', 'disast', 'alway', 'struck', 'pass', 'level'],
 ['entir',
  'upgrad',
  'game',
  'although',
  'origin',
  'music',
  'hilari',
  'much',
  'easier',
  'ear',
  'action',
  'fluid',
  'addon',
  'wacki',
  'best',
  'way',
  'point',
  'map',
  'none',
  'boss',
  'level',
  'requir',
  'purchas',
  'win',
  'realli',
  'appreci'],
 ['nice', 'game', 'love'],
 ['fun', 'play', 'addict'],
 ['like', 'new', 'version', 'fun'],
 ['best', 'game', 'world'],
 ['use',
  'good',
  'pay',
  'win',
  'play',
  'game',
  '13',
  'year',
  'take',
  'money',
  'els',
  'can',
  'not',
  'win',
  'day'],
 ['challeng', 'lot', 'fun'],
 ['fun', 'educ', 'enjoy'],
 ['one',
  'best',
  'game',
  'realli',
  'goe',
  'beyond',
  'come',
  'keep',
  'pass',
  'level',
  'abund',
  'great',
  'idea',
  'move',
  'get',
  'stuck',
  'yet',
  'reset',
  'game',
  'back',
  'level',
  'one',
  'level',
  '1',
  '010',
  'game',
  'make',
  'spend',
  'small',
  'fortun',
  'pass',
  'level',
  'made',
  'level',
  '4',
  '003',
  'afford',
  'keep',
  'play',
  'anim',
  'almost',
  'spot',
  '1',
  'million',
  'game',
  'giveaway',
  'championship'],
 ['game', 'good'],
 ['glitch', 'updat', 'suck', 'lost', 'doubl', 'blast', 'colour', 'bomb'],
 ['enjoy', 'realli', 'love'],
 ['play', 'game', 'sweet', 'honey'],
 ['love', 'game', 'nice', 'brilliant', 'thank'],
 ['divertido', 'e', 'pode', 'jogar', 'offlin'],
 ['trash', 'rip'],
 ['extrem',
  'satisfi',
  'game',
  'grandma',
  'addict',
  'start',
  'vomit',
  'candi',
  'ground'],
 ['love',
  'game',
  'play',
  'year',
  'late',
  'app',
  'annoy',
  'watch',
  'ad',
  'claim',
  'extra',
  'gold',
  'live',
  'watch',
  'cit',
  'still',
  'ask',
  'buy',
  'annoy',
  'pleas',
  'fix',
  'error',
  'demotiv'],
 ['amaz', 'game'],
 ['star',
  'good',
  'luck',
  'win',
  'anyth',
  'play',
  'candi',
  'crush',
  'often',
  'probabl',
  'said',
  'unless',
  'play',
  '24',
  'hour',
  'per',
  'day',
  'noth',
  'fun',
  'star',
  'competit',
  'ridicul',
  'consid',
  'good',
  'player',
  'almost',
  '9000',
  'know',
  'lot',
  'ahead',
  '9000',
  'know',
  'mean',
  'get',
  'peopl',
  'pay',
  'greed',
  'increas',
  '2',
  'rate',
  '3',
  'game',
  'better',
  'competit'],
 ['best', 'ever', 'play', 'want', 'smoke'],
 ['nice', 'n', 'time', 'consum', 'like', 'multi', 'task', 'ur', 'mind'],
 ['alway', 'best', 'level', '2k', 'need', 'retriev', 'program'],
 ['mani',
  'glitch',
  'current',
  '3',
  '12',
  '26',
  'spin',
  'wheel',
  'work',
  'chocol',
  'box',
  'live',
  'friend',
  'say',
  'connect',
  'connect',
  'enjoy',
  'frustrat',
  'worth',
  'play',
  '13',
  'year',
  'relax',
  'rethink',
  'worth',
  'issu',
  'need',
  'fix'],
 ['love', 'game', 'much'],
 ['extra',
  'ordinari',
  'mind',
  'fresh',
  'game',
  'ad',
  'glitch',
  'play',
  'fun',
  'play',
  'game',
  'mind',
  'recov',
  'fun'],
 ['game', 'good', 'competit'],
 ['best', 'game', 'play'],
 ['love', 'game', 'help', 'pass', 'time'],
 ['great',
  'game',
  'help',
  'boredom',
  'viru',
  'lockdown',
  'ive',
  'reach',
  'level',
  '1442',
  'without',
  'purchas',
  'still',
  'play',
  'even',
  '9',
  '1',
  '25',
  'still',
  'play',
  '22',
  '1',
  '25',
  'still',
  'play',
  '5',
  '2',
  '25',
  'still',
  'play',
  '3',
  '3',
  '25',
  'still',
  'play',
  '14',
  '3',
  '25',
  'still',
  'play',
  '24',
  '4',
  '25',
  'still',
  'play',
  '1',
  '5',
  '25',
  'ad',
  'temu',
  'infuri',
  'time',
  'hit',
  'x',
  'end',
  'reward',
  'taken',
  'straight',
  'temu',
  'web',
  'site',
  'decemb',
  'still',
  'play',
  'februari',
  'back',
  'play',
  'april',
  'play'],
 ['help', 'mind', 'relax'],
 ['happi', 'enjoy', 'game'],
 ['mind', 'relax', 'enhanc', 'creativ', 'think'],
 ['great', 'way', 'train', 'brain', 'amus', 'way'],
 ['lower', 'graphic', 'game', 'download'],
 ['wonder', 'game', 'play', 'especi', 'free', 'time'],
 ['total', 'west', 'wyu', 'u', 'put', 'phone'],
 ['pleas', 'pleas', 'let', 'game', 'gone'],
 ['thala', 'ke', 'wajah', 'se', 'ye', 'game', 'khelta', 'hu'],
 ['awesom', 'game', 'vibrant', 'color'],
 ['enjoy', 'play', 'game'],
 ['realli',
  'enjoy',
  'game',
  'could',
  'play',
  'hour',
  'get',
  'bore',
  'play',
  '10',
  'minut',
  'fine'],
 ['cooki',
  'set',
  'reset',
  'everi',
  'day',
  'day',
  'ago',
  'made',
  'sure',
  'app',
  'updat',
  'went',
  'turn',
  'cooki',
  'could',
  'next',
  'coupl',
  'day',
  'open',
  'app',
  'immedi',
  'go',
  'set',
  'privaci',
  'polici',
  'cooki',
  'set',
  'cooki',
  'matter',
  'mani',
  'time',
  'chang',
  'confirm',
  'choic',
  'anyon',
  'explain',
  'app',
  'continu',
  'track',
  'everyth',
  'despit',
  'us',
  'say',
  'seriou',
  'legal',
  'matter'],
 ['lame',
  'game',
  'play',
  'level',
  '237',
  'without',
  'lose',
  'start',
  'game',
  'level',
  '238',
  'got',
  'kick',
  'automat',
  'develop',
  'game',
  'pay',
  'attent',
  'game'],

Build Word2Vec moldel

In [ ]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)

In [ ]:
import gensim.models
# 1. Train Model
model = gensim.models.Word2Vec(sentences, min_count=1, vector_size=100, window=5, sg=0)

In [ ]:
# 2. Save Model
model.save('sentimen_tweet.w2v')

In [ ]:
# 3. Load Model
model = gensim.models.Word2Vec.load('sentimen_tweet.w2v')

In [ ]:
# 4. Model Information
w2v = model.wv
w2v.index_to_key[:10]

['game',
 'play',
 'love',
 'level',
 'fun',
 'time',
 'good',
 'candi',
 'crush',
 'get']

In [ ]:
w2v.vectors.shape, w2v.vector_size # size of vector

((1199, 100), 100)

In [ ]:
w2v.similar_by_key('game')

[('play', 0.8767953515052795),
 ('get', 0.8521837592124939),
 ('candi', 0.8520345091819763),
 ('booster', 0.8464757204055786),
 ('like', 0.8460227251052856),
 ('level', 0.8357086777687073),
 ('make', 0.8294650912284851),
 ('love', 0.8265801072120667),
 ('time', 0.8106831312179565),
 ('day', 0.8079357147216797)]

Visualize

In [ ]:
!pip install umap-learn

Requirement already satisfied: umap-learn in /usr/local/lib/python3.13/dist-packages (0.5.12)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (2.1.3)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (1.6.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from umap-learn) (4.67.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51.2->umap-learn) (0.44.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.13/dist-packages (from pynndescent>=0.5->umap-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6->umap-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.11->pynndescent>=0.5->umap-learn) (3.1.2)

In [ ]:
from umap import UMAP

In [ ]:
import numpy as np
import plotly.express as px

In [ ]:
# Tentukan jumlah kata teratas yang mau ditampilkan (misal 50 kata)
top_n = 50

# Mengambil vektor dan kata teratas saja
vectors_top = w2v.vectors[:top_n]
words_top = w2v.index_to_key[:top_n]

# Reduksi dimensi dengan UMAP
X = UMAP().fit_transform(vectors_top)

df2 = pd.DataFrame(X, columns=['umap1', 'umap2'])
df2['word'] = words_top

# Visualisasi Plotly
fig = px.scatter(df2, x='umap1', y='umap2', text='word')
fig.update_traces(textposition='top center')
fig.update_layout(height=800, title_text=f'Word2Vec Visualization (Top {top_n} Words)')
fig.show()

## **Build FastText Model**

In [ ]:
import gensim.models
import random
import numpy as np
#build model
model_fasttext = gensim.models.FastText(sentences, min_count=1,
                                        vector_size=100, window=5,
                                        min_n=3, max_n=6,
                                        sg=1, epochs=10)

In [ ]:
seed_value = 42
random.seed(seed_value)
np.random.seed(seed_value)

In [ ]:
model_fasttext = gensim.models.FastText(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=1,
    min_n=3,
    max_n=6,
    sg=1,
    epochs=10,
    workers=1,      # Mengunci multi-threading
    seed=seed_value # Mengunci bobot acak
)

In [ ]:
# 2. save model
model_fasttext.save('sentimen_tweet.fasttext')

In [ ]:
# 3. load model
model_fasttext = gensim.models.Word2Vec.load('sentimen_tweet.fasttext')

In [ ]:
# 4. model information
fastext = model_fasttext.wv
fastext.index_to_key[:10]

['game',
 'play',
 'love',
 'level',
 'fun',
 'time',
 'good',
 'candi',
 'crush',
 'get']

In [ ]:
fastext.vectors.shape

(1199, 100)

In [ ]:
fastext.similar_by_key('4g')

[('r', 0.008185291662812233),
 ('l', 0.007915041409432888),
 ('27', 0.0025305210147053003),
 ('kt', 9.051576489582658e-05),
 ('এই', -0.00027033837977796793),
 ('8171', -0.00047192294732667506),
 ('⁹', -0.0012454912066459656),
 ('9', -0.0014342969516292214),
 ('grub', -0.00207550753839314),
 ('5yr', -0.0024316171184182167)]

In [ ]:
# 5. FE result
import numpy as np
def get_document_vector(tokens, model):
    valid_vectors = [model.wv[word] for word in tokens if word in model.wv]
    # if not valid_vectors:
    #   return np.zeros(model.vector_size)
    return np.mean(valid_vectors, axis=0)
X_features = np.array([get_document_vector(doc, model_fasttext) for doc in sentences])
pd.DataFrame(X_features)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.109527,0.098213,0.064543,0.107460,0.046778,0.202323,0.029299,-0.128155,-0.133256,-0.026743,...,0.104641,0.100484,-0.005101,0.037733,0.236349,-0.096595,-0.150743,0.115858,0.063299,0.234540
1,0.114055,0.100557,0.066402,0.110161,0.047358,0.206812,0.030207,-0.130042,-0.136463,-0.028016,...,0.107399,0.102232,-0.007076,0.039500,0.240995,-0.097889,-0.154814,0.119668,0.065347,0.242051
2,0.127971,0.115815,0.075439,0.126405,0.054315,0.235835,0.033653,-0.146140,-0.153865,-0.031548,...,0.121831,0.117811,-0.010026,0.043632,0.272882,-0.111101,-0.177916,0.136940,0.072243,0.272000
3,0.122453,0.112015,0.072393,0.121807,0.051842,0.225345,0.033313,-0.141557,-0.146694,-0.031043,...,0.116178,0.112093,-0.007062,0.042601,0.262930,-0.106298,-0.169675,0.131258,0.071509,0.261198
4,0.120494,0.106334,0.069126,0.117455,0.051059,0.219242,0.032236,-0.139466,-0.145153,-0.030059,...,0.115177,0.108073,-0.007390,0.041245,0.258482,-0.104001,-0.163842,0.126731,0.069408,0.257954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.113994,0.099532,0.065453,0.110724,0.048125,0.203576,0.031352,-0.128815,-0.134282,-0.027460,...,0.105652,0.099351,-0.006745,0.040608,0.238637,-0.098638,-0.152579,0.116477,0.065698,0.239178
496,0.110807,0.099628,0.064450,0.108358,0.048460,0.204008,0.030145,-0.127159,-0.136109,-0.027615,...,0.105491,0.099883,-0.007797,0.039642,0.236376,-0.097459,-0.153581,0.118052,0.064657,0.238252
497,0.112242,0.100316,0.066831,0.109692,0.045923,0.202431,0.031115,-0.128383,-0.134990,-0.027325,...,0.107057,0.099934,-0.005869,0.040619,0.241516,-0.097815,-0.153209,0.117522,0.064569,0.238868
498,0.116023,0.103565,0.066478,0.113447,0.049389,0.212554,0.030330,-0.134186,-0.139917,-0.028969,...,0.110831,0.104706,-0.007374,0.039477,0.246402,-0.100646,-0.159096,0.122594,0.067340,0.248498
499,0.112259,0.100102,0.065657,0.109374,0.047123,0.205156,0.030161,-0.129328,-0.133915,-0.026968,...,0.106285,0.100990,-0.005162,0.038135,0.238127,-0.096405,-0.152015,0.117483,0.064988,0.238941

In [ ]:
top_n = 50

vectors_top = fastext.vectors[:top_n]
words_top = fastext.index_to_key[:top_n]

X = UMAP(random_state=42).fit_transform(vectors_top)

df2 = pd.DataFrame(X, columns=['umap1', 'umap2'])
df2['word'] = words_top

fig = px.scatter(df2, x='umap1', y='umap2', text='word')
fig.update_traces(textposition='top center')
fig.update_layout(height=800, title_text=f'FastText Visualization (Top {top_n} Words)')